name: "Build and Push to Kubernetes"
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Test step
        run: echo "Kubernetes workflow is working!"
